[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ratatui = "0.27.0"

# pathological test cases take a long time without optimizations
[profile.test]
opt-level = 1

[profile.dev]
opt-level = 1
